### ISSUE TITLE
Mention Minikube and podCIDR in the documentation

### ISSUE THREAD

**Issue by ceridwen** [projectcalico/canal#101]
## Expected Behavior

At the moment, when you try to install Canal on Minikube using the directions in the [self-hosted install](https://github.com/projectcalico/canal/blob/master/k8s-install/README.md), the kube-flannel container will fail to come up with messages in the logs about missing podCIDR.  Minikube doesn't have a flag to set podCIDR like some other ways to install Kubernetes.  I had to find [this  issue](https://github.com/coreos/flannel/issues/672) to learn that it's possible to set podCIDR on Minikube with kubectl:
`kubectl patch node minikube -p '{"spec":{"podCIDR":"10.33.12.0/24"}}'`
After I set this, I can at least connect between pods with Canal installed using netcat, though it looks to me like isolation isn't being enforced.

## Current Behavior

There's no mention of Minikube or setting podCIDR for in the documentation.

## Context

I'm trying to create a working development environment for testing network policy on my local machine so I don't have to depend on a remote cluster for doing development work.

**Comment by caseydavenport** [comment]
@ceridwen have you tried just running Calico (without flannel) on minikube?

Flannel is really just for cross-host networking so shouldn't be required for a minikube deployment.  This will remove the need to set the `podCIDR` on the node.

I know @tmjd recently had Calico working on minikube for network policy.

**Comment by tmjd** [comment]
I think the same arguments might help in this situation as I found were useful when I was working with minikube & calico.

@ceridwen You are probably already aware of  https://github.com/projectcalico/calico/issues/1013#issuecomment-325689943 but I'm putting it here for others that may come across this issue.

We currently don't have any docs in the Canal repo about using it with any integrations but I think we'd be open to adding something if you wanted to submit a PR to add that info.

**Comment by ceridwen** [comment]
@caseydavenport, I have tried to get Calico working.  After posting this yesterday, someone posted to my issue on Calico proper to say that podCIDR was probably the problem there too.  Patching with kubectl to add podCIDR does get further there, too, though the Python Kubernetes client is having problems with websockets on both Calico and Canal.  I don't know if that's a problem with the Python client, the websocket library, Calico/Canal/Flannel, or what.  I have to do some more investigation.

@tmjd, If and when I get it working (or at least isolate the problems elsewhere) I'll try to put together a PR to add the steps I took.

**Comment by tmjd** [comment]
@ceridwen With the deprecation of the Canal repo for the docs in the Calico repo (https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/canal/), I think the appropriate place for a doc that has the specifics of how to use Canal on Minikube is in the Minikube docs.  I'm going to close this issue as it is old and I believe it should be targeted elsewhere.
@ceridwen if you do have the info you were looking to add, I think a good starting place to make it available would be to add it to this issue here.  Then someone in the future could add it to the minikube docs.
