### ISSUE TITLE
Node cleanup on Kubernetes

### ISSUE THREAD

**Issue by lkoba** [projectcalico/canal#11]
I'm not sure if this is the correct place to report this since the issue is related to the calico/node DaemonSet installed by canal.

When increasing and decreasing our node count to handle for load spikes I found out that calico/node will fail if the IP address of the node was already used before. This leaves the newly added node broken.

My solution is to run this after draining and deleting a node from the cluster:

docker run --rm --net=host -e ETCD_ENDPOINTS=http://127.0.0.1:6666 calico/ctl node remove --hostname=NODE_HOSTNAME --remove-endpoints

**Comment by caseydavenport** [comment]
@lkoba Thanks for raising this.  This does affect all Calico Kubernetes deployments, as there is currently no way to detect when a node has been taken down for good or if it has only gone down temporarily.

I'll have to think a bit about what we can do to make this better, but that solution is the correct way to handle this in the meantime.

**Comment by lkoba** [comment]
The error message on calico/node included the node name associated with the IP.  It could check the Kubernetes API and run the cleanup itself if it doesn't exist or fail otherwise.

**Comment by tomdee** [comment]
Similarish to https://github.com/projectcalico/calico/issues/312

**Comment by geekofalltrades** [comment]
I'm also being affected by this issue. We have certain workloads that we isolate to their own nodes, which we dynamically turn up and shut off as needed. So, our cluster has high node churn, and this is a big pain point.

I'm going to try my hand at writing a Kubernetes controller that listens for node deletions and issues the appropriate Calico deletions.

**Comment by ejether** [comment]
@geekofalltrades  have you had any success on your controller?

**Comment by geekofalltrades** [comment]
I actually have been working on it the last couple days.

The approach I'm going for is not a controller, but a component using libcalico-go with a simple REST API that has one DELETE endpoint for nodes. The component in our infrastructure that turns nodes on and off dynamically will make calls to it every time it decommissions a node.

We're running Kubernetes 1.6.0, and I don't see that this version of Kubernetes emits an Event when a node is deleted. If it did, then I could write a completely standalone controller that would clean up the Calico datastore when it saw that event.

**Comment by ejether** [comment]
Good find! If there is some code in there you're willing or able to share please do so. Its a problem we're interested in solving and I'll contribute

**Comment by tmjd** [comment]
@geekofalltrades You may want to check on the version of etcd that you are using.  This issue https://github.com/projectcalico/calico/issues/753 was found because we were using a version of etcd less than 3.0.12 that did not generate Delete events in K8s.  Though this would only be if your k8s is not specifying a storage backend of etcdv2 (the default is to use etcdv3 for k8s).

**Comment by geekofalltrades** [comment]
Yes, indeed:
```
$ kubectl get event -n default
LASTSEEN   FIRSTSEEN   COUNT     NAME                                       KIND               SUBOBJECT   TYPE      REASON                    SOURCE                                   MESSAGE
5m         5m          1         ip-10-11-7-220.i.extrahop.com              Node                           Normal    Starting                  kubelet, ip-10-11-7-220.i.extrahop.com   Starting kubelet.
5m         5m          1         ip-10-11-7-220.i.extrahop.com              Node                           Warning   ImageGCFailed             kubelet, ip-10-11-7-220.i.extrahop.com   unable to find data for container /
5m         5m          2         ip-10-11-7-220.i.extrahop.com              Node                           Normal    NodeHasSufficientDisk     kubelet, ip-10-11-7-220.i.extrahop.com   Node ip-10-11-7-220.i.extrahop.com status is now: NodeHasSufficientDisk
5m         5m          2         ip-10-11-7-220.i.extrahop.com              Node                           Normal    NodeHasSufficientMemory   kubelet, ip-10-11-7-220.i.extrahop.com   Node ip-10-11-7-220.i.extrahop.com status is now: NodeHasSufficientMemory
5m         5m          2         ip-10-11-7-220.i.extrahop.com              Node                           Normal    NodeHasNoDiskPressure     kubelet, ip-10-11-7-220.i.extrahop.com   Node ip-10-11-7-220.i.extrahop.com status is now: NodeHasNoDiskPressure
5m         5m          1         ip-10-11-7-220.i.extrahop.com              Node                           Normal    RegisteredNode            controllermanager                        Node ip-10-11-7-220.i.extrahop.com event: Registered Node ip-10-11-7-220.i.extrahop.com in NodeController
5m         5m          1         ip-10-11-7-220.i.extrahop.com              Node                           Normal    NodeReady                 kubelet, ip-10-11-7-220.i.extrahop.com   Node ip-10-11-7-220.i.extrahop.com status is now: NodeReady
1m         1m          1         ip-10-11-7-220.i.extrahop.com              Node                           Normal    Starting                  kubelet, ip-10-11-7-220.i.extrahop.com   Starting kubelet.
1m         1m          1         ip-10-11-7-220.i.extrahop.com              Node                           Warning   ImageGCFailed             kubelet, ip-10-11-7-220.i.extrahop.com   unable to find data for container /
1m         1m          2         ip-10-11-7-220.i.extrahop.com              Node                           Normal    NodeHasSufficientDisk     kubelet, ip-10-11-7-220.i.extrahop.com   Node ip-10-11-7-220.i.extrahop.com status is now: NodeHasSufficientDisk
1m         1m          2         ip-10-11-7-220.i.extrahop.com              Node                           Normal    NodeHasSufficientMemory   kubelet, ip-10-11-7-220.i.extrahop.com   Node ip-10-11-7-220.i.extrahop.com status is now: NodeHasSufficientMemory
1m         1m          2         ip-10-11-7-220.i.extrahop.com              Node                           Normal    NodeHasNoDiskPressure     kubelet, ip-10-11-7-220.i.extrahop.com   Node ip-10-11-7-220.i.extrahop.com status is now: NodeHasNoDiskPressure
1m         1m          1         ip-10-11-7-220.i.extrahop.com              Node                           Warning   Rebooted                  kubelet, ip-10-11-7-220.i.extrahop.com   Node ip-10-11-7-220.i.extrahop.com has been rebooted, boot id: b201c4c2-06bf-462c-aca4-6d4fbfd3686a
1m         1m          1         ip-10-11-7-220.i.extrahop.com              Node                           Normal    NodeNotReady              kubelet, ip-10-11-7-220.i.extrahop.com   Node ip-10-11-7-220.i.extrahop.com status is now: NodeNotReady
1m         1m          1         ip-10-11-7-220.i.extrahop.com              Node                           Normal    NodeReady                 kubelet, ip-10-11-7-220.i.extrahop.com   Node ip-10-11-7-220.i.extrahop.com status is now: NodeReady
56s        56s         1         ip-10-11-7-220.i.extrahop.com              Node                           Normal    RemovingNode              controllermanager                        Node ip-10-11-7-220.i.extrahop.com event: Removing Node ip-10-11-7-220.i.extrahop.com from NodeController
```

Lots of tasty events for Nodes in the `default` Namespace.

That `RemovedNode` event is what I want... now I need to experiment to make sure that it's only emitted when nodes are deleted, and not also when they just go missing temporarily.

**Comment by caseydavenport** [comment]
@geekofalltrades you can also watch nodes themselves, rather than events.

e.g. 

```
kubectl get nodes --watch
```

That should generate `watch.Event` structs for you.  We do this here: https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/k8s/syncer.go#L98

**Comment by caseydavenport** [comment]
FYI I've hacked up a (very prototype) node controller for Calico here: https://github.com/caseydavenport/calico-node-controller

**Comment by mingfang** [comment]
I just got him by this and I think this is a critical problem.

**Comment by cdenneen** [comment]
@caseydavenport any fixes in queue for this? having issue with latest kops

**Comment by tmjd** [comment]
Checkout https://docs.projectcalico.org/master/reference/kube-controllers/configuration, take note that is the master docs (not in an official release yet).  To answer your question, yes there is something in the queue. :grinning:

**Comment by cdenneen** [comment]
@tmjd Thanks... I'm actually more referring to https://github.com/kubernetes/kops/issues/2661 and https://github.com/kubernetes/kops/issues/3224 and fix the temporary dns issues seen currently.

**Comment by caseydavenport** [comment]
Yeah, there is a fix in master that will be included in upcoming releases.

Once released, we should update kops as well.
