### ISSUE TITLE
remove deprecated content from this repo

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/canal#124]
This repository is deprecated, and the canal project has moved to `projectcalico/calico` repository.

The warning on this repo is good, but we should remove the content (docs & manifests).

**Comment by ozdanborne** [comment]
Lets figure out if anyone is directly linking to `kubectl apply -f` these manifests before we make this change...

**Comment by jakesyl** [comment]
Can we add this?

**Comment by jakesyl** [comment]
https://joshrendek.com/2018/04/kubernetes-on-bare-metal/ offending link
