### ISSUE TITLE
Kubernetes v1.11 Failed validation

### ISSUE THREAD

**Issue by miry** [projectcalico/canal#129]
During installation of CNI there is validation error:

```shell
$ kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://raw.githubusercontent.com/projectcalico/canal/master/k8s-install/1.7/canal.yaml

error: error validating "https://raw.githubusercontent.com/projectcalico/canal/master/k8s-install/1.7/canal.yaml": error validating data: ValidationError(CustomResourceDefinition): unknown field "description" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinition; if you choose to ignore these errors, turn validation off with --validate=false
```

Cluster installed via kubeadm v1.11.0.

**Comment by tmjd** [comment]
Is there a reason you aren't not using the manifest hosted at https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/flannel?  This repo has been deprecated for the installation docs at the linked docs.

If you think you need to use the manifest located here you should just be able to remove the description field(s) that is causing that validation failure.

**Comment by caseydavenport** [comment]
@tmjd yep, that's right.

I think we should remove the manifests from this repo now that it's been deprecated for several months. They're out-of-date now :)

**Comment by miry** [comment]
@tmjd because I follow the documentation: https://github.com/projectcalico/canal/tree/master/k8s-install since Kube version 1.6. Thanks for link. I will check it.
