### ISSUE TITLE
is it possible to add canal to an existing cluster that uses flannel?

### ISSUE THREAD

**Issue by xaka** [projectcalico/canal#130]
I have an old k8s cluster that's running in production. It uses cni + flannel for networking. It's been decided that we need to have network policies, which flannel doesn't support.

I'm curious whether it's possible to add calico/canal to an existing cluster that uses flannel already?

Thanks.

**Comment by tmjd** [comment]
It is not a simple matter to switch to canal from flannel.  I am not aware of any way to do this on an existing cluster and maintain connectivity. It basically requires a full networking swap.
