### ISSUE TITLE
some minor issues found in canal.yaml

### ISSUE THREAD

**Issue by renmaosheng** [projectcalico/canal#27]
In canal.yaml: 
1. it seems 10-canal.conf should be 10-calico.conf. the calico node will read 10-calico.conf. 
2. in older kubernetes version like 1.3.0, "_" is not supported, so it is better to change "cni_network_config" to "cni-network-config"

I would like to propose a fix for above issue.

**Comment by caseydavenport** [comment]
@renmaosheng thanks for raising.

1) Are you seeing trouble with this? The name of the file shouldn't affect anything AFAIK.  The calico/node container doesn't actually look at that file.  The contents are passed by the kubelet to the CNI plugin.

2) I'm not sure that this matters too much - the self-hosted installation is only supported on Kubernetes v1.4.0+ anyway (it won't work on v1.3.0 for other reasons).

**Comment by renmaosheng** [comment]
Hi Casey,  just realized it doesn't work with k8s 1.3.0, not sure what is the problem, but I have verified the basic functions of network policy works fine in v1.3.0.  I can switch to 1.4.0. 

I remembered the I hit some issue about the file name, and changed it to fix. But that is long ago. let me retry it.
