### ISSUE TITLE
Using calico-node v1.0.0 routes are not added

### ISSUE THREAD

**Issue by brad-peters** [projectcalico/canal#30]
I'm doing some simple evaluation of calico, flannel and canal.  

I am using the following versions of everything:

etcd - 3.0.15  api version 2
flanneld - v0.6.2
calico-node - v1.0.0

I am using the CNI plugins script priv-net-run.sh to run two simple netcat tests one "nc -l 88" and another "nc <container_ip> 88" to ensure traffics gets between the containers.

When I setup flanneld and calico independently following their docs and they both work fine.  When I try the canal docs [https://github.com/projectcalico/canal/blob/master/InstallGuide.md](url) but with the current versions I cannot get my second container to talk to my first container.

Using tcpdump I see ARP requests for 169.254.1.1 being made but there is no reply.  There are also no entries in my route table for the container ips.

If I switch and use v0.22.0 of calico then the ARP requests are answered and the container routes appear in the routing table.

All of my tests are done in a Centos 7.3 virtual box.

**Comment by caseydavenport** [comment]
> Using tcpdump I see ARP requests for 169.254.1.1 being made but there is no reply. There are also no entries in my route table for the container ips

This indicates to me that Felix is not aware of the containers on that host, and thus isn't programming the proxy_arp sysctl and routing table entires for each Calico WorkloadEndpoint.

I'd be interested in seeing the output of the following commands:

```
calicoctl get weps -o wide
calicoctl get node -o wide
```

It might also be useful to take a look at the Felix logs to see if it is behaving properly.  Probably something like this:

```
kubectl logs canal-node-abcdef -c calico-node
```

**Comment by brad-peters** [comment]
Here are the outputs of those commands:

```
[root@localhost flanneld]# ETCD_ENDPOINTS=http://<ip>:2379 calicoctl get weps -o wide
NODE           ORCHESTRATOR   WORKLOAD           NAME   NETWORKS         NATS   INTERFACE         PROFILES   
<ip>           cni            6a261af62d5d41a6   eth0   10.100.54.2/32          cali6a261af62d5   canal      

[root@localhost flanneld]# ETCD_ENDPOINTS=http://<ip>:2379 calicoctl get node -o wide                          
NAME           ASN       IPV4           IPV6   
<host-name>   (64511)    <ip>          
<ip>      
```

I'm not using kubernetes, is there another way to get the felix logs?

**Comment by caseydavenport** [comment]
Yep.  Depending on how you're running felix, it should either put the logs in `/var/log/calico` or output to stdout (e.g `docker logs`).

I'm assuming that <ip> in your nodes matches up with <ip> in the endpoints output?

**Comment by brad-peters** [comment]
Thanks.  I found the logs but have a mix of v0.22.0 and v1.0.0 in there.  I will have to redo my tests to get a clean set of logs.

**Comment by tmjd** [comment]
ping @brad-peters
Has this issue been resolved?  I understand that the more likely thing is that you haven't had time to redo your tests yet.
If it has been resolved, please feel free to close this issue.  Thanks.

**Comment by brad-peters** [comment]
Sorry I didn't get a chance to get back to it and won't for a bit.  You can close this out if you want.  I can always reopen if do see it again.
