### ISSUE TITLE
k8s self-hosted install doesn't install Flannel CNI plugin binary

### ISSUE THREAD

**Issue by braedon** [projectcalico/canal#32]
https://github.com/projectcalico/canal/blob/master/k8s-install/canal.yaml uses `calico/cni:v1.4.2` to install CNI, but this version doesn't include the Flannel CNI binary. Without the binary installed DNS can't start (and presumably networking doesn't work). Later versions of the image include the Flannel CNI binary.

**Comment by caseydavenport** [comment]
Yep, this should just be a matter of updating the version of the calico/cni container we use and doing a bit of testing.

@heschlie can you add this to your plate?

**Comment by heschlie** [comment]
Resolved in #33
