### ISSUE TITLE
Wrong tag or image in canal-etcdless.yaml

### ISSUE THREAD

**Issue by smirgel** [projectcalico/canal#34]
Latest canal-etcdless.yaml (commit 1afff9f48832e5f85e99504dbd6b1cb211053036) points to a non-existing tag for the flannel-git image: "quay.io/coreos/flannel-git:v0.7.0".
I've checked against the quay.io registry and there is no such tag. However the flannel images has such a tag so I'm guessing that is what was intended? That is: "quay.io/coreos/flannel:v0.7.0"

**Comment by caseydavenport** [comment]
Yes, that is what is intended.

@heschlie could you update the image?

**Comment by heschlie** [comment]
@caseydavenport #35 is up for your review

**Comment by caseydavenport** [comment]
Merged, should be fixed now!

**Comment by smirgel** [comment]
Thanks!
