### ISSUE TITLE
Canal local host routing issue

### ISSUE THREAD

**Issue by kfox1111** [projectcalico/canal#38]
I am using the following template:
https://raw.githubusercontent.com/projectcalico/canal/master/k8s-install/canal-etcdless.yaml

The cluster seems to work just fine except any contact from a pod running on host N without net=host can not access the host N by ip. Cross host contact seems to work fine though. Tested with multiple values of N.

For example, for pod prometheus:
/prometheus # ifconfig eth0 | grep addr:[0-1]
          inet addr:10.244.2.11  Bcast:0.0.0.0  Mask:255.255.255.255

# kubectl get pods -o wide | grep 10.244.2.11
prometheus-server-2167327372-zbvcw                             2/2       Running   0          18d       10.244.2.11     192.168.0.3

/prometheus # ping 192.168.0.3 -c 5
PING 192.168.0.3 (192.168.0.3): 56 data bytes
--- 192.168.0.3 ping statistics ---
5 packets transmitted, 0 packets received, 100% packet loss

cross host though works:
/prometheus # ping 192.168.0.4 -c 5
PING 192.168.0.4 (192.168.0.4): 56 data bytes
64 bytes from 192.168.0.4: seq=0 ttl=63 time=0.275 ms
64 bytes from 192.168.0.4: seq=1 ttl=63 time=0.242 ms
64 bytes from 192.168.0.4: seq=2 ttl=63 time=0.295 ms
64 bytes from 192.168.0.4: seq=3 ttl=63 time=0.275 ms
64 bytes from 192.168.0.4: seq=4 ttl=63 time=0.303 ms
--- 192.168.0.4 ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 0.242/0.278/0.303 ms

**Comment by caseydavenport** [comment]
@kfox1111 could you try adding this to the environment of the calico/node container?

```
# Set Felix endpoint to host default action to ACCEPT.
- name: FELIX_DEFAULTENDPOINTTOHOSTACTION
  value: "ACCEPT"
```

By default, Felix prevents containers from talking to their own host.  This will change that behavior.

**Comment by tmjd** [comment]
@kfox1111 it sounds like there is a solution to the issue you were having so I am going to close this issue for now.  If setting the above does not resolve this issue please feel free to reopen.
