### ISSUE TITLE
bootkube : installation

### ISSUE THREAD

**Issue by rmenn** [projectcalico/canal#39]
There seems to be an example for kubeadm, would be great if there was an example for bootkube

**Comment by tomdee** [comment]
I agree! See also this issue from the bootkube side - https://github.com/kubernetes-incubator/bootkube/issues/407

**Comment by v1k0d3n** [comment]
man, this would be awesome...we're in the same place as @rmenn, where we're trying to use bootkube. it's been pretty challenging for things outside of flannel. we're specifically targeting calico, but we'd really like to see any supported CNI as parameterized options in bootkube.

**Comment by v1k0d3n** [comment]
guys, we haven't revisited this in a while...but i have been working on a side repo to bootkube which basically shows how this would/could be done. the repo is to CI a bootkube provided cluster, plus any number of post installation actions (the repo is just starting), i could write the document the procedures if folks are interested. @gunjan5 and @kprabhak may be interested in this. it includes calico as well.

https://github.com/v1k0d3n/bootkube-ci
