### ISSUE TITLE
Should document + set resource requests in our calico/node manifests

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/canal#40]
A discussed in https://github.com/projectcalico/calico/issues/617, we should be setting resource requests in our manifests.  It makes a large difference to our latency on highly CPU constrained systems.

**Comment by fasaxc** [comment]
Assigning to @tomdee for triage.  Since this seems to make such a dramatic difference, I think this should be a ship-stopper for Calico 2.2.

**Comment by tomdee** [comment]
Yes, let's do it ASAP

**Comment by fasaxc** [comment]
@tomdee Why did you assign this back to me?  I'm not the right person to own a canal issue, I know next to nothing about it.

**Comment by tomdee** [comment]
Because you tested CPU allocations for felix? But I guess Casey ended up making the change for Calico manifests, someone just needs to make the same change for the Canal manifests.
