### ISSUE TITLE
Sync <1.6 yaml with the 1.6 yaml 

### ISSUE THREAD

**Issue by kfox1111** [projectcalico/canal#48]
The patch "Sync <1.6 yaml with the 1.6 yaml " broke the kolla-kubernetes gate. Reverting it fixed the issue. I think there may be an incompatibility with the canal containers and k8s 1.5?

**Comment by djosborne** [comment]
@kfox1111 The images it was updated to use should be compatible with k8s 1.5. What behavior / logs are you seeing?

**Comment by kfox1111** [comment]
Console logs of a failed job:
http://logs.openstack.org/23/450423/1/check/gate-kolla-kubernetes-deploy-ubuntu-binary-2-ceph-nv/a425103/console.html

Individual pod logs and pod describes here:
http://logs.openstack.org/23/450423/1/check/gate-kolla-kubernetes-deploy-ubuntu-binary-2-ceph-nv/a425103/logs/pods/

**Comment by tomdee** [comment]
@kfox1111 Could you describe what's actually going wrong. There are a lot of logs at those links but I have no idea what I'm looking for.

**Comment by djosborne** [comment]
A quick look and I noticed `kubedns` pod wasn't coming up, which is a symptom of this issue: https://github.com/projectcalico/calicoctl/issues/1575

I've opened #49 to resolve it

**Comment by djosborne** [comment]
@kfox1111 I've just merged 49, which adds the following environment variable to `calico/node`:
```
# Set Felix endpoint to host default action to ACCEPT.
name: FELIX_DEFAULTENDPOINTTOHOSTACTION
value: "ACCEPT"
```
This should allow connections from the container to the host, e.g. Kube-DNS on Master speaking to the Api-server. I believe this is the issue you were hitting.

Please retry with the latest manifests and reopen if you are still having some issues.
