### ISSUE TITLE
kube-flannel CrashLoopBackOff on bare-metal install

### ISSUE THREAD

**Issue by mellotron** [projectcalico/canal#64]
Hello,

I've deployed Kubernetes 1.6.2 on a brand new metal node with kubeadm with:

$ sudo kubeadm init --pod-network-cidr 10.244.0.0/16

...and did the steps in this document:

- https://github.com/projectcalico/canal/tree/master/k8s-install

I then get:

kubectl -n kube-system logs po/canal-khsqt kube-flannel                                                                                                                                                       
E0501 20:55:21.603770       1 main.go:127] Failed to create SubnetManager: failed to read net conf: open /etc/kube-flannel/net-conf.json: no such file or directory

What am I doing incorrectly?

**Comment by sbezverk** [comment]
I see the same issue..

kubectl logs -n kube-system canal-xmj40 kube-flannel
E0501 23:38:45.468237       1 main.go:127] Failed to create SubnetManager: failed to read net conf: open /etc/kube-flannel/net-conf.json: no such file or directory

What information is expected to be in this file?

**Comment by sbezverk** [comment]
It seems canal-config configmap is missing this section:

  net-conf.json: |
    {
      "Network": "10.57.128.0/19",
      "Backend": {
        "Type": "vxlan"
      }
    }
After adding it to the manifest canal is running properly.

**Comment by caseydavenport** [comment]
@mellotron @sbezverk whoops! I think that section was accidentally removed as part of #62.

**Comment by sbezverk** [comment]
@caseydavenport Any chance you gets fixed really soon ;)? I do not want to start hacking configmap to resolve it.

**Comment by caseydavenport** [comment]
@sbezverk please see #66 and let me know if that fixes your problem!

**Comment by sbezverk** [comment]
Yep, looks good.

**Comment by sbezverk** [comment]
@caseydavenport any idea when this change gets merged?

**Comment by mellotron** [comment]
@caseydavenport I think you got the indentation off by a bit in 1.6. This puts net-conf.json in 10-calico.conf:

$ cat /etc/cni/net.d/10-calico.conf 
{
    "name": "k8s-pod-network",
    "type": "calico",
    "log_level": "info",
    "datastore_type": "kubernetes",
    "hostname": "arosa",
    "ipam": {
        "type": "host-local",
        "subnet": "usePodCidr"
    },
    "policy": {
        "type": "k8s",
        "k8s_auth_token": "..."
    },
    "kubernetes": {
        "k8s_api_root": "https://10.96.0.1:443",
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
    }
}

# Flannel network configuration. Mounted into the flannel container.
net-conf.json: |
  {
    "Network": "10.244.0.0/16",
    "Backend": {
      "Type": "vxlan"
    }
  }

**Comment by mellotron** [comment]
If I manually place net-conf.json in /etc/cni/net.d/, the canal pod arrives at 3/3 READY, however kube-dns never moves from Pending to Running.

**Comment by mellotron** [comment]
Within "describe nodes", I see:

runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

**Comment by mellotron** [comment]
The above seems related to https://github.com/kubernetes/kubernetes/issues/43815 , if I remove  KUBELET_NETWORK_ARGS, the node becomes ready, however I wasn't having this issue with flannel so something must be broken in the canal CNI deployment?

**Comment by caseydavenport** [comment]
@mellotron thanks for pointing out the indentation - I've updated the PR with a fix.

The `net-conf.json` file should go in `/etc/kube-flannel/` inside the flannel container. 

The missing network config should have been installed by the [`install-cni` container](https://github.com/caseydavenport/canal/blob/44e0ab1a29c79960a9831916c8bc851b69e22c00/k8s-install/1.6/canal.yaml#L132). 

Do you see the config file at `/etc/cni/net.d` on the host?
