### ISSUE TITLE
post location of current canal.yaml in the file

### ISSUE THREAD

**Issue by sbezverk** [projectcalico/canal#65]
Hello,

Our gating system downloads the latest version of canal.yaml automatically with each job. When you change the location of canal.yaml, it breaks our gate and we need to change the code to point to the new location. Would it be possible to to post new location in the special static file in your repo?  SO when you change canal.yaml location it gets automatically changed in that file as well. In this case we can read this file in the gate code and always get right location without any manual changes.
Thank you
Serguei

**Comment by djosborne** [comment]
@sbezverk sorry for the move. We are trying to deprecate the name "etcdless". 

I agree that the file shouldn't move again unless it has some kind of deprecation phase to prevent problems like this. Hosting a description of the static link is an interesting idea, and I will consider it. I'm not sure what the solution we go with will be. There is an ever increasing number of manifests with subtle differences between them, so I think we are overdue for a better system.

Anywho, I'll leave this issue open as a reminder that **we shouldn't move manifests around before exercising a deprecation phase**.
