### ISSUE TITLE
Migrate from etcd datastore to Kubernetes API

### ISSUE THREAD

**Issue by camilocot** [projectcalico/canal#71]
Some months ago, I set up canal in Kubernetes 1.4 using etcd datastore. I'd like to upgrade kubernetes to v1.5 and start using kubernetes API as a backend in canal. Is there any guide to migrate our current configuration from etcd to Kubernetes API ?

This manifest was used to deploy canal: https://github.com/projectcalico/canal/blob/3d0918025c522b40674f0e26579802dddc3d6326/k8s-install/kubeadm/canal.yaml

**Comment by tmjd** [comment]
There is no migration path from etcd backend to the K8s backend currently.  There are several features in Calico that are not possible with the K8s backend that are possible with the etcd backend so it would not be an option in all scenarios.  Perhaps when the K8s backend fully supports all Calico features a conversion process might be created.

Is there a reason, besides just removing the etcd dependency for calico, that you want to eliminate etcd?

**Comment by camilocot** [comment]
Not really, but canal readme file recommends using the Kubernetes API manifests so I wanted to plan the migration if necessary. Thanks.
