### ISSUE TITLE
Canal on OpenShift 

### ISSUE THREAD

**Issue by prasenforu** [projectcalico/canal#86]
I found some ppt which tells that I can use canal on OpenShift.

Can you please share instructions for canal deployment on OpenShift.

**Comment by kprabhak** [comment]
@prasenforu Are you referring to the slides from the OpenShift Commons briefing from March? If so, the slide there refers to Canal with Flannel+Kubernetes.

Adapting to the Flannel as deployed with openshift would likely require some additional steps, but I reckon it might be possible. Something along the lines of:
1. Deploying openshift with flannel (say, using openshift-ansible)
2. Deploying canal manifest
3. Creating additional policy to allow various openshift artifacts (router, registry, etc.) in admin namespace to function.
@ozdanborne Any thoughts?

**Comment by prasenforu** [comment]
Can  not recall right now but I can remember in that slide mr. Bean picture was there. :)

**Comment by prasenforu** [comment]
Found the link https://blog.openshift.com/wp-content/uploads/Fluentd_-Cloud-Native-Logging.pdf

**Comment by ozdanborne** [comment]
It is technically possible to deploy canal in openshift, but you will have to do so manually. Unfortunately we do not have any other information available at this time.

**Comment by prasenforu** [comment]
I am ready to do manually, can you provide some steps please.
