### ISSUE TITLE
Add some docs about issue submission and expected process

### ISSUE THREAD

**Issue by tmjd** [projectcalico/canal#89]
It would be nice to add some documentation about the expected issue submission process and what a submitter should expect.

## Expected Behavior
There is documentation (or links to projectcalico documentation) about the issue submission process and a general expectation of the process.

## Current Behavior
I didn't find any such documentation.

## Possible Solution
Some notes in the readme or links to the projectcalico general information for this.

## Context
Submitted issue was missed initially, see https://github.com/projectcalico/canal/issues/77#issuecomment-318040428.

**Comment by caseydavenport** [comment]
This isn't just a canal issue, but for the projectcalico/* org in its entirety.

**Comment by caseydavenport** [comment]
It exists now as part of the PR template, as well as various contributing guides in github.com/projectcalico/calico.
